platform:
  - x86
  - x64

environment:
  nodejs_version: "8"

cache:
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'
  - node_modules

branches:
  only:
    - master

skip_non_tags: true

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install

build_script:
  - echo %WINDOWS_CERTIFICATE_FILE% | base64.exe --decode > cert.pfx
  - npm run publish
